### ISSUE TITLE
defining synopsis

### ISSUE THREAD

**Issue by rbonthond** [mlawren/p5-OptArgs#11]
I'm seeing the following code to display the synopsis, but I'm not able to figure out how to actually set this

```
$usage .= "\n  ${grey}Synopsis:$reset\n    $desc{$caller}\n"
  if $ishelp and $desc{$caller};
```

What do I need to set in my script to get this Synopsis line displayed?

**Comment by mlawren** [comment]
Hi Robbin,

The Synopsis can only be displayed for sub-commands because there is no
way at the moment to set the $desc{$caller} key for the top-level
command.

The reason why that feature is missing is because I hadn't yet decided
how the caller should define the string. For sub-commands the Synopsis
string is extracted from the "comment" field, but the top-level command
doesn't have that to use.

Now that I have thought about it a bit I guess I would propose a simple
additional function "synopsis":

    use OptArgs;

    synopsis 'does foo to bar';

    arg command => (...);

    opt help => (...);

Perhaps it should also be called "comment" to make it consistent with
the sub-commands... What makes sense to you?

In a more general sense, not being able to change the error and/or
usage messages should also be classified as a bug or a feature request,
depending on one's outlook in life. However the determination of the
message elements, and the actual message presentation, are lumped
together inside the _usage() function.  That function doesn't take any
callbacks or export the details in a useful form. Something that I will
change for OptArgs2, whenever I start working on it.

Cheers,
Mark.
-- 
Mark Lawrence

**Comment by rbonthond** [comment]
hi,

perhaps something similair to that's done with help?
opt usage => ( comment => "synopsis", hidden =>1, usage =>1 );

robbin

**Comment by mlawren** [comment]
So, I won't win any records for resolving this issue quickly, and you may well have moved on ... but OptArgs2 version 2.0.0 is about to be uploaded to CPAN, with support for synopsis functionality throughout.

However, the 2 series comes with a whole new API, so in theory I'm closing this issue against OptArgs (original) as a kind of 'wontfix'. _If_ you do have heaps of code relying on OptArgs (original) and still want this functionality in there let me know.
